export default function WikiFrameworksPage() {
  return (
    <div className="space-y-6 min-w-0">
      <section className="rounded-3xl border border-white/10 bg-white/5 p-6">
        <h1 className="text-3xl font-semibold text-white">Framework and Benchmark Terms</h1>
        <p className="mt-3 text-sm text-slate-300 max-w-4xl">
          These terms define the data dimensions used in the dashboard filters, tables, and charts. They describe what exactly is being compared so that benchmark results are not interpreted out of context. A framework label alone is not enough for analysis; the version, platform preset, route, and iteration all affect the result.
        </p>
      </section>

      <section className="rounded-3xl border border-white/10 bg-white/5 p-6">
        <dl className="grid gap-4 md:grid-cols-2">
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <dt className="font-semibold text-white">Run Folder</dt>
            <dd className="mt-1 text-sm text-slate-300">A timestamped benchmark execution batch. It groups all summary rows that were produced during one benchmark campaign. In the dashboard it acts as the primary scope boundary for single-run analysis.</dd>
          </div>
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <dt className="font-semibold text-white">Framework + Version</dt>
            <dd className="mt-1 text-sm text-slate-300">The technology variant under test, such as nextjs-v15.1.4. The version matters because benchmark behavior can change across releases even when the framework name stays the same.</dd>
          </div>
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <dt className="font-semibold text-white">Preset</dt>
            <dd className="mt-1 text-sm text-slate-300">The Lighthouse execution profile, typically mobile or desktop. Presets are not interchangeable because throttling, viewport size, and device assumptions affect the score landscape.</dd>
          </div>
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <dt className="font-semibold text-white">Route</dt>
            <dd className="mt-1 text-sm text-slate-300">The application page path that was benchmarked. Routes should be compared only against the same route because different pages can load different amounts of content and logic.</dd>
          </div>
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <dt className="font-semibold text-white">Iteration</dt>
            <dd className="mt-1 text-sm text-slate-300">The repeated execution index for the same route/framework/preset tuple. Iterations are used to capture natural variability and make distributions visible instead of relying on a single measurement.</dd>
          </div>
          <div className="rounded-xl border border-white/10 bg-white/5 p-4">
            <dt className="font-semibold text-white">Artifact</dt>
            <dd className="mt-1 text-sm text-slate-300">The raw JSON, HTML, or CSV report generated by Lighthouse for a single test row. These artifacts are the evidence layer behind the dashboard and are used to explain score changes and audit outcomes.</dd>
          </div>
        </dl>
      </section>

      <section className="rounded-3xl border border-white/10 bg-white/5 p-6">
        <h2 className="text-xl font-semibold text-white">Interpretive rule</h2>
        <p className="mt-3 text-sm leading-6 text-slate-300">
          A valid comparison requires the same route, the same preset, and an adequate number of iterations. Framework conclusions based on mixed routes or mixed device profiles are not scientifically valid because they confound the independent variable with other sources of variation.
        </p>
      </section>
    </div>
  );
}
